### ISSUE TITLE
Thank you very much for your work

### ISSUE THREAD

**Issue by 1158755456** [WuZhuoran/awesome-gaze#2]
Thank you very much for your work.
If I want to train myself what network model to use, the recognition effect will be better?

**Comment by WuZhuoran** [comment]
Hi @1158755456 ,

Thanks for your notice. I am not sure about your overall requirement. 
But among all the codebase, I do recommend [GazeML](https://github.com/swook/GazeML)

That one is easy to setup, easy to train and test and show as demo.

**Comment by WuZhuoran** [comment]
Also, [Eye Tracking for Everyone](https://github.com/CSAILVision/GazeCapture) is also a good start for different network.
